export const prices = {
   'Ensalada de Verdura': 10.25,
   'Vieiras a la plancha': 15.12,
   'Tartaleta de champiñones': 12.00,
   'Risotto de setas salvajes con queso': 18.00,
   'Ensalada de langosta con aguacate': 22.20,
   'Crema de calabaza asada': 14.15,
   'Salmón al horno y puré de patatas': 20.25,
   'Solomillo de ternera a la parrilla': 25.00,
   'Paella marinera con langostinos': 23.00,
   'Tarta de chocolate negro': 10.00,
   'Crème brûlée de vainilla con caramelo': 9.30,
   'Soufflé de limón con coulis de mango y chantilly': 11.99,
   'Malbec argentino, cosecha reserva': 30.25,
   'Chardonnay francés, Grand Cru': 35.02,
   'Cabernet Sauvignon chileno, reserva especial': 28.05,
   'Mojito clásico con hojas de menta fresca y lima': 8.58,
   'Martini seco con aceitunas verdes.': 10.36,
   'Agua mineral con gas, con una rodaja de limón.': 5.00,
};